common/models/Content.php
<?php

namespace common\models;

/**
 * This is the model class for table "site_content".
 *
 * @property int $id
 * @property string $type
 * @property int|null $parent_id
 * @property string|null $settings
 * @property string $template
 * @property string $layout
 * @property string $view
 * @property string $resource_type
 * @property int $sort
 * @property int|null $status
 * @property int $deleted
 * @property int $cacheable
 * @property int $searchable
 * @property string|null $created_on
 * @property int $created_by
 * @property string|null $updated_on
 * @property int $updated_by
 */
class Content extends \base\libs\RedisDB
{
    public $_slug;
    public $default_title;
    public $posts_column;
    public $posts_sorting;
    public $products_sorting;
    public $posts_per_page;
    public $products_per_page;
    public $products_view_type;
    public $subcategories_view_type;
    public $segment_relations;

    public static $selected_language = 'en';

    /**
     * Table name
     *
     * @return string
     */
    public static function tableName()
    {
        return 'site_content';
    }

    /**
     * Rules
     *
     * @return array
     */
    public function rules()
    {
        return [
            [['created_on', 'updated_by', 'segment_relations'], 'safe'],
            [['sort', 'type'], 'required'],
            [['parent_id', 'sort', 'status', 'deleted', 'searchable', 'cacheable', 'created_by', 'updated_by'], 'integer'],
            [['template', 'layout', 'view', 'posts_column', 'posts_sorting', 'posts_per_page', 'subcategories_view_type', 'products_view_type', 'products_sorting', 'products_per_page'], 'string'],
            [['searchable', 'cacheable'], 'default', 'value' => 1],
            [['parent_id', 'status', 'sort', 'deleted'], 'default', 'value' => 0],
            [['template', 'layout', 'view', 'resource_type'], 'default', 'value' => ''],
            [['settings'], 'default', 'value' => []],
            ['created_on', 'default', 'value' => date('Y-m-d H:i:s')],
            ['updated_on', 'default', 'value' => date('Y-m-d H:i:s')],
        ];
    }

    /**
     * Attribute labels
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => _e('ID'),
            'title' => _e('Title'),
            'settings' => _e('Settings'),
            'parent_id' => _e('Parent'),
            'sort' => _e('Sort'),
            'status' => _e('Status'),
            'deleted' => _e('Deleted'),
            'searchable' => _e('Searchable'),
            'created_on' => _e('Created on'),
            'created_by' => _e('Created by'),
            'updated_on' => _e('Updated on'),
            'updated_by' => _e('Updated by'),
            'template' => _e('Template'),
            'layout' => _e('Layout'),
            'view' => _e('View file'),
            'resource_type' => _e('Resource type'),
            'posts_column' => _e('Posts column'),
            'posts_sorting' => _e('Posts sorting'),
            'posts_per_page' => _e('Posts per page'),
            'subcategories_view_type' => _e('Subcategories view type'),
            'products_view_type' => _e('Products view type'),
            'products_sorting' => _e('Products sorting'),
            'products_per_page' => _e('Products per page'),
        ];
    }

    /**
     * Redis db relationship
     *
     * @return mixed
     */
    public function redisDbRelationship() {
        return array(new ContentFields(), new ContentInfos(), new SegmentRelations());
    }
    
    /**
     * Get content info
     *
     * @return void
     */
    public function getInfo()
    {
        return $this->hasOne(ContentInfos::className(), ['content_id' => 'id']);
    }

    /**
     * Get parent
     *
     * @return void
     */
    public function getParent()
    {
        return $this->hasOne(self::className(), ['id' => 'parent_id']);
    }

    /**
     * Get parent
     *
     * @return void
     */
    public function getParentInfo()
    {
        return $this->hasOne(ContentInfos::className(), ['content_id' => 'id'])
            ->via('parent');
    }

    /**
     * Resource types
     *
     * @return array
     */
    public static function resourceTypes($content_type = null)
    {
        $output = array(
            'default' => _e('Default'),
        );

        if (is_null($content_type) || $content_type == 'page') {
            $output = array(
                'default' => _e('Default'),
                'home_page' => _e('Home page'),
                'start_page' => _e('Start page'),
                'error_page' => _e('Error page'),
            );

            $content_types = self::contentTypes();

            if ($content_types) {
                foreach ($content_types as $content_type) {
                    $key = array_value($content_type, 'key');
                    $lexicon = array_value($content_type, 'lexicon');
                    $title = array_value($lexicon, 'title');

                    if ($key && $key != 'page' && $title) {
                        $output[$key] = $title;
                    }
                }
            }
        }

        return $output;
    }

    /**
     * Content types
     *
     * @return array
     */
    public static function contentTypes()
    {
        $default_types = [
            array(
                'key' => 'page',
                'slug' => 'page',
                'slug_generator' => 'self',
                'items_with_parent' => true,
                'image_fields' => array('image', 'cover_image'),
                'segments' => array(),
                'lexicon' => array(
                    'title' => _e('Pages'),
                    'menu_title' => _e('Pages'),
                    'new_item_title' => _e('New page'),
                    'edit_item_title' => _e('Edit page'),
                    'edit_item_title2' => _e('Edit page: {title}'),
                    'successfully_created' => _e('The page was created successfully.'),
                    'successfully_updated' => _e('The page has been successfully updated.'),
                    'back_to_message' => _e('Back to pages'),
                    'not_found_message' => _e('Page not found.'),
                    'not_found_message_full' => _e('The page you were looking for does not exist, unavailable for you or deleted.'),
                ),
            ),
            array(
                'key' => 'post',
                'slug' => 'post',
                'slug_generator' => 'self',
                'items_with_parent' => false,
                'image_fields' => array('image', 'cover_image'),
                'segments' => array(
                    'post_category' => array(
                        'label' => _e('Categories'),
                        'input' => 'select', // select, select-multiple
                        'required' => 0,
                    ),
                    'post_tag' => array(
                        'label' => _e('Tags'),
                        'input' => 'select-multiple', // select, select-multiple
                        'required' => 0,
                    ),
                ),
                'lexicon' => array(
                    'title' => _e('Posts'),
                    'menu_title' => _e('Posts'),
                    'new_item_title' => _e('New post'),
                    'edit_item_title' => _e('Edit post'),
                    'edit_item_title2' => _e('Edit post: {title}'),
                    'successfully_created' => _e('The post was created successfully.'),
                    'successfully_updated' => _e('The post has been successfully updated.'),
                    'back_to_message' => _e('Back to posts'),
                    'not_found_message' => _e('Post not found.'),
                    'not_found_message_full' => _e('The post you were looking for does not exist, unavailable for you or deleted.'),
                ),
            )
        ];

        $content_types = theme_configs('content_types');

        if (is_array($content_types) && $content_types) {
            return array_merge($content_types, $default_types);
        }

        return $default_types;
    }
}

backend/controllers/ContentController.php
<?php

namespace backend\controllers;

use base\BackendController;
use backend\models\Content;
use common\models\ContentInfos;
use Yii;
use yii\data\Pagination;
use yii\helpers\Url;

/**
 * Content controller
 */
class ContentController extends BackendController
{
    public $url;
    public $settings;
    public $content_type;
    public $items_with_parent;

    /**
     * Before action
     *
     * @param $action
     * @return void
     */
    public function beforeAction($action)
    {
        $settings = array();
        $type = Yii::$app->request->get('type');

        if (!is_null($type) && $type) {
            $type = trim($type);
            $type = trim($type, '/');

            $content_types = Content::contentTypes();
            $settings = filter_array($content_types, ['slug' => $type], true);
        }

        if ($settings) {
            $this->settings = $settings;
            $this->url = "/content/{$type}";
            $this->content_type = array_value($settings, 'key');

            Content::$type = $this->content_type;
            Content::$items_with_parent = array_value($settings, 'items_with_parent');
            Content::$slug_generator = array_value($settings, 'slug_generator');
        }

        return parent::beforeAction($action);
    }

    /**
     * Displays all page
     *
     * @return string
     */
    public function actionAll()
    {
        $bulk_actions = array('publish', 'unpublish', 'trash');
        $where = ['content.deleted' => 0];

        if ($this->settings) {
            return $this->page('all', $where, $bulk_actions);
        } else {
            return $this->errorPage();
        }
    }

    /**
     * Displays published page
     *
     * @return string
     */
    public function actionPublished()
    {
        $bulk_actions = array('unpublish', 'trash');
        $where = ['content.status' => 1, 'content.deleted' => 0];

        if ($this->settings) {
            return $this->page('published', $where, $bulk_actions);
        } else {
            return $this->errorPage();
        }
    }

    /**
     * Displays unpublished page
     *
     * @return string
     */
    public function actionUnpublished()
    {
        $bulk_actions = array('publish', 'trash');
        $where = ['content.status' => 0, 'content.deleted' => 0];

        if ($this->settings) {
            return $this->page('unpublished', $where, $bulk_actions);
        } else {
            return $this->errorPage();
        }
    }

    /**
     * Displays deleted page
     *
     * @return string
     */
    public function actionDeleted()
    {
        $bulk_actions = array('publish', 'unpublish', 'restore', 'delete');
        $where = ['content.deleted' => 1];

        if ($this->settings) {
            return $this->page('deleted', $where, $bulk_actions);
        } else {
            return $this->errorPage();
        }
    }

    /**
     * Page
     *
     * @param string $type
     * @param array $where_query
     * @param array $bulk_actions
     * @param array $where_in
     * @return void
     */
    public function page($type, $where_query, $bulk_actions, $where_in = array())
    {
        $main_url = Url::to([$this->url]);

        $limit_default = 20;
        $sort_default = 'a-z';

        $ajax = input_post('ajax');
        $limit = input_get('limit', $limit_default);

        $args = ['sort' => $sort_default];
        $query = Content::getItems('', $args)->andWhere($where_query);

        if (is_array($where_in) && $where_in) {
            $query->andWhere($where_in);
        }

        $count = $query->count();

        if ($ajax == 'bulk-actions') {
            $ajax_action = input_post('action');
            $ajax_items = input_post('items');
            $ajax_item_id = input_post('id');
            $items = explode(',', $ajax_items);

            $output = Content::ajaxAction($ajax_action, $ajax_item_id, $items);

            echo json_encode($output);
            exit();
        }

        if (!empty($limit)) {
            $pagination = new Pagination(['totalCount' => $count, 'pageSize' => $limit]);
        } else {
            $pagination = new Pagination(['totalCount' => $count]);
        }

        $content = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        $page_types = Content::getPageTypes($type);

        return $this->render('page', array(
            'main_url' => $main_url,
            'page_types' => $page_types,
            'bulk_actions' => $bulk_actions,
            'limit_default' => $limit_default,
            'sort_default' => $sort_default,
            'content' => $content,
            'pagination' => $pagination,
        ));
    }

    /**
     * Displays create page
     *
     * @return string
     */
    public function actionCreate()
    {
        $main_url = Url::to([$this->url]);
        $all_url = Url::to([$this->url . '/all']);

        if (!$this->settings) {
            return $this->errorPage();
        }

        $model = new Content();
        $info = new ContentInfos();
        $post_item = Yii::$app->request->post();
        $lexicon = array_value($this->settings, 'lexicon');

        if ($post_item) {
            $submit_button = input_post('submit_button');

            $flash_type = 'success-error';
            $flash_message = _e('An error occurred while processing your request. Please try again.');

            if ($model->load($post_item) && $info->load($post_item)) {
                $id = Content::createItem($model, $info, $post_item);

                $flash_type = 'success-alert';
                $flash_message = array_value($lexicon, 'successfully_created');

                Yii::$app->session->setFlash($flash_type, $flash_message);

                if ($submit_button == 'create_and_add_new') {
                    return $this->refresh();
                } else {
                    $url = rtrim($main_url, '/') . "/edit/?id={$id}";

                    if ($info->language) {
                        $url .= "&lang={$info->language}";
                    }

                    return $this->redirect($url);
                }
            }

            Yii::$app->session->setFlash($flash_type, $flash_message);
            return $this->refresh();
        }

        $this->registerJs(array(
            'dist/libs/tinymce/tinymce.min.js',
            'theme/components/tinymce-editor.js',
        ));

        return $this->render('create', array(
            'all_url' => $all_url,
            'main_url' => $main_url,
            'model' => $model,
            'info' => $info,
        ));
    }

    /**
     * Displays edit page
     *
     * @return string
     */
    public function actionEdit()
    {
        $main_url = Url::to([$this->url]);
        $all_url = Url::to([$this->url . '/all']);

        if (!$this->settings) {
            return $this->errorPage();
        }

        $id = Yii::$app->request->get('id');
        $post_item = Yii::$app->request->post();

        $item = Content::getItemToEdit($id);
        $model = array_value($item, 'model');
        $info = array_value($item, 'info');
        $translations = array_value($item, 'translations');
        $lexicon = array_value($this->settings, 'lexicon');

        if (!$model || !$info) {
            return $this->render('error', array(
                'all_url' => $all_url,
                'main_url' => $main_url,
            ));
        }

        if ($post_item) {
            $model->cacheable = 0;
            $model->searchable = 0;
            $submit_button = input_post('submit_button');

            $flash_type = 'success-error';
            $flash_message = _e('An error occurred while processing your request. Please try again.');

            if ($model->load($post_item) && $info->load($post_item)) {
                $action = Content::updateItem($model, $info, $post_item);

                if (is_string($action) && $action) {
                    $flash_type = 'error-alert';
                    $flash_message = $action;
                } else {
                    $flash_type = 'success-alert';
                    $flash_message = array_value($lexicon, 'successfully_updated');
                }
            }

            Yii::$app->session->setFlash($flash_type, $flash_message);

            if ($submit_button == 'create_and_add_new') {
                return $this->redirect(['create']);
            } else {
                return $this->refresh();
            }
        }

        $this->registerJs(array(
            'dist/libs/tinymce/tinymce.min.js',
            'theme/components/tinymce-editor.js',
        ));

        return $this->render('update', array(
            'all_url' => $all_url,
            'main_url' => $main_url,
            'model' => $model,
            'info' => $info,
            'translations' => $translations,
        ));
    }
}

backend/views/content/create.php
<?php
$controller = Yii::$app->controller;
$lexicon = array_value($controller->settings, 'lexicon');

$this->title = array_value($lexicon, 'new_item_title');
$this->page_title = array_value($lexicon, 'new_item_title') . ': ';
$this->breadcrumbs[] = ['label' => array_value($lexicon, 'title'), 'url' => $all_url]; ?>

<div class="Page-create">
    <?= $this->render('_form', [
        'all_url' => $all_url,
        'main_url' => $main_url,
        'model' => $model,
        'info' => $info,
    ]); ?>
</div>

backend/views/content/error.php
<?php
$controller = Yii::$app->controller;
$lexicon = array_value($controller->settings, 'lexicon');

$this->title = _e('Not found');
$this->breadcrumbs[] = ['label' => array_value($lexicon, 'edit_item_title'), 'url' => $main_url]; ?>

<div class="card">
    <div class="card-body page-item-not-found">
        <i class="ri-error-warning-line"></i>
        <h3><?= array_value($lexicon, 'not_found_message'); ?></h3>
        <p><?= array_value($lexicon, 'not_found_message_full'); ?></p>

        <a href="<?= $all_url; ?>" class="btn btn-secondary waves-effect btn-with-icon">
            <i class="ri-arrow-left-line mr-1"></i>
            <?= array_value($lexicon, 'back_to_message'); ?>
        </a>
    </div>
</div>

backend/views/content/page.php
<?php

use backend\widgets\BulkActions;
use common\models\ContentInfos;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$langs = admin_active_langs('content_lexicon');
$lexicon = admin_content_lexicon('lang_code');

$controller = Yii::$app->controller;
$content_lexicon = array_value($controller->settings, 'lexicon');
$items_with_parent = array_value($controller->settings, 'items_with_parent');

$this->title = array_value($content_lexicon, 'title'); ?>

<div class="card-top-links row">
    <div class="col-md-7">
        <div class="card-listed-links">
            <?php foreach ($page_types as $page_type_key => $page_type) : ?>
                <a href="<?= $main_url . '/' . $page_type_key; ?>" <?= $page_type['active'] ? 'class="active"' : ''; ?>>
                    <?= $page_type['name']; ?>
                    <span>(<?= $page_type['count']; ?>)</span>
                </a>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="col-md-5">
        <div class="card-listed-links-right">
            <a href="<?= $main_url; ?>/create" class="btn btn-info waves-effect">
                <?= _e('Add new') ?>
            </a>
            <a href="<?= admin_url(); ?>" class="btn btn-secondary waves-effect">
                <?= _e('Close') ?>
            </a>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="card-body-top">
            <?= BulkActions::widget(array(
                'actions' => $bulk_actions,
                'limit_default' => $limit_default,
                'sort_default' => $sort_default
            )); ?>
        </div>

        <div class="table-responsive table-with-actions">
            <input type="hidden" id="table-selected-items" ta-selected-items>

            <table class="table mb-0">
                <thead class="thead-light">
                    <tr>
                        <th width="30px" class="ta-select-icon">
                            <i class="ri-checkbox-blank-line" data-ta-select-all></i>
                        </th>
                        <th><?= _e('Name') ?></th>
                        <?php if ($items_with_parent) : ?>
                            <th><?= _e('Parent'); ?></th>
                        <?php endif; ?>
                        <?php
                        if ($langs) {
                            foreach ($langs as $lang) {
                                echo '<th width="50" class="text-center">';
                                echo '<img src="' . $lang['flag'] . '" alt="' . $lang['name'] . '" height="10">';
                                echo '</th>';
                            }
                        } ?>
                        <th class="text-center" width="80px"><?= _e('Status'); ?></th>
                        <th width="180px"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($content) : ?>
                        <?php foreach ($content as $key => $one) : ?>
                            <?php
                            $status_text = _e('Published');
                            $status_class = 'dot-status-success';

                            if ($one->deleted) {
                                $status_text = _e('Deleted');
                                $status_class = 'dot-status-danger';
                            } elseif ($one->status == 0) {
                                $status_text = _e('Unpublished');
                                $status_class = 'dot-status-warning';
                            }

                            if ($one->info) {
                                $info = $one->info;
                            } else {
                                $info = ContentInfos::find()
                                    ->where(['content_id' => $one->id])
                                    ->one();
                            }

                            $edit_url = $main_url . "/edit/?id={$one->id}";
                            $created_on = date_create($one->created_on); ?>
                            <tr>
                                <td class="ta-select-icon">
                                    <i class="ri-checkbox-blank-line" data-ta-select="<?= $one->id ?>"></i>
                                </td>
                                <td>
                                    <a href="<?= $edit_url; ?>&lang=<?= $lexicon; ?>" class="products-table-title " title="<?= $info->title ?>">
                                        <?= $info->title ? $info->title : '-'; ?>
                                    </a>
                                    <nav class="nav products-table-nav">
                                        <?php if ($items_with_parent) : ?>
                                            <li class="text-secondary align-items-center">
                                                <?= _e('Child items'); ?>: <?= count_content_childs($one, 'child_count'); ?>
                                            </li>
                                        <?php endif; ?>
                                        <li class="text-secondary align-items-center" title="<?= _e('Created date'); ?>">
                                            <i class="ri-calendar-2-line mr-1"></i><?= date_format($created_on, 'd/m/y H:i'); ?>
                                        </li>
                                    </nav>
                                </td>
                                <?php if ($items_with_parent) : ?>
                                    <td>
                                        <?= (isset($one->parentInfo->title) && $one->parentInfo->title) ? $one->parentInfo->title : '-' ?>
                                    </td>
                                <?php endif; ?>
                                <?php if ($langs) : ?>
                                    <?php
                                    $translations_array = array();
                                    $translations = ContentInfos::find()->where(['content_id' => $one->id])->all();

                                    if ($translations) {
                                        foreach ($translations as $translation_item) {
                                            $translations_array[$translation_item->language] = $translation_item->title;
                                        }
                                    } ?>
                                    <?php foreach ($langs as $lang) : ?>
                                        <?php $lang_code = $lang['lang_code'] ?>
                                        <td width="20" class="text-center">
                                            <a href="<?= $edit_url; ?>&lang=<?= $lang_code; ?>" class="table-lang-icon">
                                                <?php if (isset($translations_array[$lang_code])) : ?>
                                                    <i class="ri-edit-2-fill" data-toggle="tooltip" data-placement="bottom" title="<?= $translations_array[$lang_code]; ?>"></i>
                                                <?php else : ?>
                                                    <i class="ri-menu-add-line" data-toggle="tooltip" data-placement="bottom" title="<?= _e('No translation'); ?>"></i>
                                                <?php endif; ?>
                                            </a>
                                        </td>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                                <td class="text-center">
                                    <span class="<?= $status_class; ?>" data-toggle="tooltip" data-placement="bottom" title="<?= $status_text; ?>"></span>
                                </td>
                                <td class="ta-icons-block">
                                    <?php if ($items_with_parent) : ?>
                                        <div class="ta-icons-in">
                                            <a href="<?= $main_url; ?>/create/?parent=<?= $one->id ?>">
                                                <i class="ri-add-circle-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Add child page'); ?>"></i>
                                            </a>
                                        </div>
                                        <div class="ta-icons-in">
                                            <a href="<?= set_query_var('parent', $one->id); ?>">
                                                <i class="ri-list-unordered" data-toggle="tooltip" data-placement="top" title="<?= _e('Child pages'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                    <div class="ta-icons-in">
                                        <a href="<?= get_content_url($info, 'admin_lexicon'); ?>" target="_blank">
                                            <i class="ri-share-box-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Open on the site'); ?>"></i>
                                        </a>
                                    </div>
                                    <?php if ($one->status == 1) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="unpublish" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-eye-off-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Unpublish'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php elseif ($one->status == 0) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="publish" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-checkbox-circle-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Publish'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($one->deleted) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="restore" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-refresh-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Restore'); ?>"></i>
                                            </a>
                                        </div>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="delete" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-delete-bin-2-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Delete permanently'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php else : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="trash" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-delete-bin-6-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Move to trash'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <tr>
                            <td colspan="<?= (5 + count($langs)); ?>" class="text-center table-not-found">
                                <i class="ri-error-warning-line"></i>
                                <div class="h5">
                                    <?= array_value($content_lexicon, 'not_found_message'); ?>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<nav>
    <?php echo LinkPager::widget([
        'pagination' => $pagination,
        'options' => ['class' => 'pagination pagination-rounded'],
        'linkContainerOptions' => ['class' => 'page-item'],
        'linkOptions' => ['class' => 'page-link'],
        'prevPageLabel' => '<i class="ri-arrow-left-s-line"></i>',
        'nextPageLabel' => '<i class="ri-arrow-right-s-line"></i>',
        'disabledListItemSubTagOptions' => ['tag' => 'a', 'class' => 'page-link'],
    ]); ?>
</nav>