backend/models/Subject.php
<?php

namespace backend\models;

use common\models\SubjectInfo;
use common\models\Subject as CommonSubject;

/**
 * Subject model
 */
class Subject extends CommonSubject
{
    public static $type;

    /**
     * Get items
     *
     * @param string $page_type
     * @return object
     */
    public static function getItems($page_type = '', $args = array())
    {
        $search = input_get('s');
        $sort = input_get('sort');
        $department = input_get('department');

        $admin_current_lang = admin_current_lang();

        self::$selected_language = array_value($admin_current_lang, 'lang_code', 'en');

        if (empty($sort) && array_value($args, 'sort')) {
            $sort = array_value($args, 'sort');
        }

        if (empty($department) && array_value($args, 'department')) {
            $department = array_value($args, 'department');
        }

        $query = self::find()
            ->with(['department.infoRelation'])
            ->join('INNER JOIN', 'subject_info info', 'info.subject_id = subject.id');

        $query->andWhere(['language' => self::$selected_language]);

        if (is_numeric($department) && $department > 0) {
            $query->andWhere(['subject.department_id' => $department]);
        }

        if ($search) {
            $query->andWhere(['like', 'info.name', $search]);
        } 
        
        if ($sort == 'a-z') {
            $sort_query = ['info.name' => SORT_ASC];
        } elseif ($sort == 'z-a') {
            $sort_query = ['info.name' => SORT_DESC];
        } elseif ($sort == 'oldest') {
            $sort_query = ['subject.created_on' => SORT_ASC];
        } else {
            $sort_query = ['subject.created_on' => SORT_DESC];
        }

        $query->orderBy($sort_query);
        // rawsql($query);
        return $query;
    }

    /**
     * Page types
     *
     * @param string $active_key
     * @return array
     */
    public static function getPageTypes($active_key = '')
    {
        $page_types = array(
            'index' => array(
                'name' => _e('All'),
                'active' => false,
                'count' => self::itemsCount(['subject.deleted' => 0]),
            ),
            'published' => array(
                'name' => _e('Published'),
                'active' => false,
                'count' => self::itemsCount(['subject.deleted' => 0, 'subject.status' => 1]),
            ),
            'unpublished' => array(
                'name' => _e('Unpublished'),
                'active' => false,
                'count' => self::itemsCount(['subject.deleted' => 0, 'subject.status' => 0]),
            ),
            'deleted' => array(
                'name' => _e('Deleted'),
                'active' => false,
                'count' => self::itemsCount(['subject.deleted' => 1]),
            ),
        );

        if (isset($page_types[$active_key])) {
            $page_types[$active_key]['active'] = true;
        }

        return $page_types;
    }



    /**
     * Create item
     *
     * @param [type] $model
     * @param [type] $info
     * @param [type] $post_item
     * @return int
     */
    public static function createItem($model, $info, $post_item = array())
    {
        $log_data = array();
        $now_date = date('Y-m-d H:i:s');
        $current_user_id = current_user_id();
        $active_languages = admin_active_langs();

        // Create model
        $model->created_on = $now_date;
        $model->created_by = $current_user_id;
        $model->updated_on = $now_date;
        $model->updated_by = $current_user_id;

        if ($model->save()) {
            $log_data['subject']['attrs'] = $model->getAttributes();
            $log_data['subject']['old_attrs'] = array();

            // Create translations
            if ($active_languages) {

                foreach ($active_languages as $active_language) {

                    $lang_code = $active_language['lang_code'];

                    $new = new SubjectInfo();
                    $new->subject_id = $model->id;
                    $new->language = $lang_code;
                    $new->name = $info->name[$lang_code];
                    $new->description = $info->description[$lang_code];

                    if ($new->save()) {
                        $log_data['subject_info'][$new->language]['attrs'] = $new->getAttributes();
                        $log_data['subject_info'][$new->language]['old_attrs'] = array();
                    }else{
                        dd($new->errors);
                    }
                }
            }

            // Set log
            set_log('admin', [
                'res_id' => $model->id,
                'type' => 'subject',
                'action' => 'create',
                'data' => json_encode($log_data),
            ]);

        }else{
            dd($model->errors);
        }

        return $model->id;
    }

    /**
     * Update item
     *
     * @param [type] $model
     * @param [type] $info
     * @param [type] $post_item
     * @return int
     */
    public static function updateItem($model, $info, $post_item = array())
    {
        $log_data = array();
        $now_date = date('Y-m-d H:i:s');
        $active_languages = admin_active_langs();
        $current_user_id = current_user_id();

        // Save model
        $model->updated_on = $now_date;
        $model->updated_by = $current_user_id;

        $modelOldAttributes = $model->getOldAttributes();

        if ($model->save()) {
            $log_data['subject']['attrs'] = $model->getAttributes();
            $log_data['subject']['old_attrs'] = $modelOldAttributes;

            // Create translations
            if ($active_languages) {

                foreach ($active_languages as $active_language) {

                    $lang_code = $active_language['lang_code'];

                    $infoSingleLang = SubjectInfo::find()->where(['subject_id' => $model->id, 'language' => $lang_code])->one();
                    if($infoSingleLang){
                        $infoSingleLang->name = $info->name[$lang_code];
                        $infoSingleLang->description = $info->description[$lang_code];

                        $infoOldAttributes = $infoSingleLang->getOldAttributes();

                        if ($infoSingleLang->save()) {
                            $log_data['subject_info'][$infoSingleLang->language]['attrs'] = $infoSingleLang->getAttributes();
                            $log_data['subject_info'][$infoSingleLang->language]['old_attrs'] = $infoOldAttributes;
                        }else{
                            dd($infoSingleLang->errors);
                        }
                    }
                    
                }
            }

            // Set log
            set_log('admin', [
                'res_id' => $model->id,
                'type' => 'subject',
                'action' => 'update',
                'data' => json_encode($log_data),
            ]);
        }else{
            dd($model->errors);
        }

        return $model->id;
    }

    /**
     * Get item to edit
     *
     * @param int $id
     * @return array
     */
    public static function getItemToEdit($id)
    {
        $current_language = admin_current_lang();
        $lang_code = array_value($current_language, 'lang_code', 'en');

        $model = self::findOne($id);
        $info = new SubjectInfo();
        $translations = SubjectInfo::find()->where(['subject_id' => $id])->all();
        $names = [];
        $descriptions = [];
        foreach ($translations as $translation) {
            $names[$translation['language']] = $translation['name'];
            $descriptions[$translation['language']] = $translation['description'];
        }

        $info->name = $names;
        $info->description = $descriptions;

        $output['model'] = $model;
        $output['info'] = $info;
        $output['translations'] = $translations;

        return $output;
    }


    /**
     * Count all
     *
     * @param array $where
     * @return int
     */
    public static function itemsCount($where = array(), $where_in = array())
    {
        $query = self::find()
            ->join('INNER JOIN', 'subject_info info', 'info.subject_id = subject.id');

        if (is_array($where) && $where) {
            $query->andWhere($where);
        }

        if (is_array($where_in) && $where_in) {
            $query->andWhere($where_in);
        }

        $query->groupBy('info.subject_id');
        return $query->count();
    }



    /**
     * Ajax actions
     *
     * @param string $action
     * @param int $id
     * @param mixed $items
     * @return array
     */
    public static function ajaxAction($action, $id, $items)
    {
        $output['error'] = true;
        $output['success'] = false;

        if ($action == 'unpublish') {
            $output['error'] = false;
            $output['success'] = true;

            if (is_numeric($id) && $id > 0) {
                $item = self::findOne($id);
                self::bulkActionWithSubject('unpublish', $item);

                $output['message'] = _e('Item unpublished successfully.');
            } elseif (!empty($items)) {
                for ($i = 0; $i < count($items); $i++) {
                    $item = self::findOne($items[$i]);
                    self::bulkActionWithSubject('unpublish', $item);
                }

                $output['message'] = _e('Selected items have been successfully unpublished.');
            }
        } elseif ($action == 'publish') {
            $output['error'] = false;
            $output['success'] = true;

            if (is_numeric($id) && $id > 0) {
                $item = self::findOne($id);
                self::bulkActionWithSubject('publish', $item);

                $output['message'] = _e('Item published successfully.');
            } elseif (!empty($items)) {
                for ($i = 0; $i < count($items); $i++) {

common/models/Subject.php
<?php

namespace common\models;

use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "subject".
 *
 * @property int $id
 * @property int|null $type
 * @property string|null $code
 * @property int|null $department_id
 * @property int|null $practical_hours
 * @property int|null $theoretical_hours
 * @property int $sort
 * @property int|null $status
 * @property int $deleted
 * @property string|null $created_on
 * @property int $created_by
 * @property string|null $updated_on
 * @property int $updated_by
 */
class Subject extends \base\libs\RedisDB
{

    public static $selected_language = 'en';

    /**
     * Table name
     *
     * @return string
     */
    public static function tableName()
    {
        return 'subject';
    }

    /**
     * Rules
     *
     * @return array
     */
    public function rules()
    {
        return [
            [['sort'], 'required'],
            [['created_on', 'updated_by'], 'safe'],
            [['code'], 'string'],
            [['department_id', 'practical_hours', 'theoretical_hours', 'sort', 'status', 'deleted', 'created_by', 'updated_by'], 'integer'],
            [['status', 'sort', 'deleted','type'], 'default', 'value' => 0],
            ['created_on', 'default', 'value' => date('Y-m-d H:i:s')],
            ['updated_on', 'default', 'value' => date('Y-m-d H:i:s')],
        ];
    }

    /**
     * Attribute labels
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => _e('ID'),
            'type' => _e('Type'),
            'code' => _e('Code'),
            'department_id' => _e('Department'),
            'practical_hours' => _e('Practical hours'),
            'theoretical_hours' => _e('Theoretical hours'),
            'sort' => _e('Sort'),
            'status' => _e('Status'),
            'deleted' => _e('Deleted'),
            'created_on' => _e('Created on'),
            'created_by' => _e('Created by'),
            'updated_on' => _e('Updated on'),
            'updated_by' => _e('Updated by'),
        ];
    }

    /**
     * Get content infos
     *
     * @return void
     */
    public function getInfos()
    {
        return $this->hasMany(SubjectInfo::class, ['subject_id' => 'id']);
    }

    /**
     * Get content info
     *
     * @return void
     */
    public function getInfoRelation()
    {
        self::$selected_language = array_value(admin_current_lang(), 'lang_code', 'en');
        return $this->hasMany(SubjectInfo::class, ['subject_id' => 'id'])
                    ->andOnCondition(['language' => self::$selected_language]);
    }

    /**
     * Get info
     *
     * @return void
     */
    public function getInfo()
    {
        return $this->infoRelation[0];
    }

    /**
     * Get department
     *
     * @return void
     */
    public function getDepartment()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id']);
    }

    /**
     * Get all hours
     *
     * @return void
     */
    public function getAllHours()
    {
        $practicalHours = ($this->practical_hours) ?? 0;
        $theoreticalHours = ($this->theoretical_hours) ?? 0;
        return $practicalHours + $theoreticalHours;
    }

    /**
     * Get all hours
     *
     * @return void
     */
    public function getHoursText()
    {
        $practicalHours = ($this->practical_hours) ?? 0;
        $theoreticalHours = ($this->theoretical_hours) ?? 0;
        return '<b>' . $this->allHours . '</b> (' .  _e('Practical hours') . ': <b>' . $practicalHours . '</b>, '.  _e('Theoretical hours') . ': <b>' . $theoreticalHours . '</b>)';
    }

    /**
     * Get all items
     *
     * @param int $lang
     * @return array
     */
    public static function listAll($lang = null){
        
        $lang = $lang ?? self::$selected_language;
        $result = self::find()
            ->join('INNER JOIN', 'subject_info info', 'info.subject_id = subject.id')
            ->select('subject.*, info.*')
            ->where([
                'and',
                ['info.language' => $lang]
            ])
            ->asArray()->all();
        $list = [];
        foreach ($result as $one) {
            $list[$one['id']] = $one['name'];
        }
        return $list;
    }

    /**
     * Status array
     *
     * @param int $key
     * @return array
     */
    public function statusArray($key = null)
    {
        $array = [
            1 => _e('Active'),
            0 => _e('Inactive'),
        ];

        if (isset($array[$key])) {
            return $array[$key];
        }

        return $array;
    }

}

backend/views/education/subjects/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

$languages = admin_active_langs();
$langs_array = ArrayHelper::map($languages, 'lang_code', 'name');
$content_language = admin_content_lexicon('lang_code');

if ($model->isNewRecord) {
    $model->sort = 0;
    $model->created_by = Yii::$app->user->id;
    $model->updated_by = Yii::$app->user->id;
    $info->language = $content_language;
}

// Languages
$lang = input_get('lang');

if (is_string($lang) && $lang) {
    $info->language = $lang;
}

// Parent id
$parent_id = input_get('parent');

if (is_numeric($parent_id) && $parent_id > 0) {
    $model->parent_id = $parent_id;
}

// Begin form
$form = ActiveForm::begin([
    'options' => [
        'class' => 'full-form',
    ],
]); ?>



<div class="row">
    <!-- Left column -->
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-tabs-custom nav-justified mb-3" role="tablist">
                    <?php foreach($languages as $lang){?>
                        <li class="nav-item">
                            <a class="nav-link <?php if($content_language == $lang['lang_code']) echo "active"?>" data-toggle="tab" href="#tab_<?=$lang['lang_code']?>" role="tab">
                                <span class="d-none d-sm-block">
                                    <img src="<?= $lang['flag']; ?>" alt="<?= $lang['lang_code']; ?>" height="10" width="17">
                                    <?=$lang['name']?>
                                </span>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
                <!-- /Nav tabs -->

                <div class="tab-content">
                    <?php foreach($languages as $lang){?>
                        <!-- Tab item -->
                        <div class="tab-pane <?php if($content_language == $lang['lang_code']) echo "active"?>" id="tab_<?=$lang['lang_code']?>" role="tabpanel">
                            <div class="form-group required-field">
                                <?= $form->field($info, 'name['.$lang['lang_code'].']')->textInput(['required' => 'required', 'ep-bind-action' => 'title']) ?>
                            </div>

                            <div class="form-group">
                                <?= $form->field($info, 'description['.$lang['lang_code'].']')->textarea(['id' => 'info-description-textarea-'.$lang['lang_code']]) ?>

                            </div>
                        
                        </div>
                        <!-- /Tab item -->
                    <?php } ?>
                
                </div>
                
                
                

            </div>
        </div>



    </div>
    <!-- /Left column -->

    <!-- Right column -->
    <div class="col-md-3">

        <div class="card">
            <div class="card-body">

                <div class="form-group">
                    <?= $form->field($model, 'practical_hours')->textInput() ?>
                </div>

                <div class="form-group">
                    <?= $form->field($model, 'theoretical_hours')->textInput() ?>
                </div>

                <div class="form-group required-field">
                    <?= $form->field($model, 'status')->dropDownList($model->statusArray(), ['class' => 'form-control custom-select', 'required' => 'required']) ?>
                </div>

                <div class="form-group required-field">
                    <?= $form->field($model, 'sort')->textInput(['type' => 'number', 'required' => 'required']) ?>
                </div>
            </div>
        </div>

    </div>
    <!-- /Right column -->
</div>

<div class="mb-3 full-form-btns">
    <?php
    if ($model->isNewRecord) {
        echo Html::submitButton('<i class="ri-check-line mr-1"></i> ' . _e('Create'), ['class' => 'btn btn-success waves-effect btn-with-icon']);
        echo Html::submitButton('<i class="ri-add-circle-line mr-1"></i> ' . _e('Create & add another'), ['class' => 'btn btn-primary waves-effect btn-with-icon', 'name' => 'submit_button', 'value' => 'create_and_add_new']);
    } else {
        echo Html::submitButton('<i class="ri-check-line mr-1"></i> ' . _e('Save'), ['class' => 'btn btn-success waves-effect btn-with-icon']);
        echo Html::submitButton('<i class="ri-add-fill mr-1"></i> ' . _e('Save & add another'), ['class' => 'btn btn-primary waves-effect btn-with-icon', 'name' => 'submit_button', 'value' => 'create_and_add_new']);
    } ?>
</div>
<?php ActiveForm::end(); ?>

backend/views/education/subjects/create.php
<?php
$controller = Yii::$app->controller;

$this->title = _e('Create subject');
$this->page_title = $this->title;
$this->breadcrumbs[] = ['label' => _e('Subjects'), 'url' => $main_url]; ?>

<div class="Page-create">
    <?= $this->render('_form', [
        'main_url' => $main_url,
        'model' => $model,
        'info' => $info
    ]); ?>
</div>

backend/views/education/subjects/error.php
<?php
$controller = Yii::$app->controller;
$lexicon = array_value($controller->settings, 'lexicon');

$this->title = _e('Not found');
$this->breadcrumbs[] = ['label' => array_value($lexicon, 'edit_item_title'), 'url' => $main_url]; ?>

<div class="card">
    <div class="card-body page-item-not-found">
        <i class="ri-error-warning-line"></i>
        <h3><?= array_value($lexicon, 'not_found_message'); ?></h3>
        <p><?= array_value($lexicon, 'not_found_message_full'); ?></p>

        <a href="<?= $all_url; ?>" class="btn btn-secondary waves-effect btn-with-icon">
            <i class="ri-arrow-left-line mr-1"></i>
            <?= array_value($lexicon, 'back_to_message'); ?>
        </a>
    </div>
</div>

backend/views/education/subjects/page.php
<?php

use backend\widgets\BulkActions;
use common\models\DirectionInfo;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$lexicon = admin_content_lexicon('lang_code');
$admin_current_lang = admin_current_lang('lang_code');

$controller = Yii::$app->controller;

$this->title = _e('Subjects'); 
?>

<div class="card-top-links row">
    <div class="col-md-7">
        <div class="card-listed-links">
            <?php foreach ($page_types as $page_type_key => $page_type) : ?>
                <a href="<?= $main_url . '/' . $page_type_key; ?>" <?= $page_type['active'] ? 'class="active"' : ''; ?>>
                    <?= $page_type['name']; ?>
                    <span>(<?= $page_type['count']; ?>)</span>
                </a>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="col-md-5">
        <div class="card-listed-links-right">
            <a href="<?= $main_url; ?>/create" class="btn btn-info waves-effect">
                <?= _e('Add new') ?>
            </a>
            <a href="<?= admin_url(); ?>" class="btn btn-secondary waves-effect">
                <?= _e('Close') ?>
            </a>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="card-body-top">

            <?= BulkActions::widget(array(
                'actions' => $bulk_actions,
                'limit_default' => $limit_default,
                'sort_default' => $sort_default
            )); ?>
        </div>

        <div class="table-responsive table-with-actions">
            <input type="hidden" id="table-selected-items" ta-selected-items>

            <table class="table mb-0">
                <thead class="thead-light">
                    <tr>
                        <th width="30px" class="ta-select-icon">
                            <i class="ri-checkbox-blank-line" data-ta-select-all></i>
                        </th>
                        <th><?= _e('Name') ?></th>
                        <th><?= _e('Hours') ?></th>
                        <th class="text-center" width="80px"><?= _e('Status'); ?></th>
                        <th width="180px"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($content) : ?>
                        <?php foreach ($content as $key => $one) : ?>
                            <?php
                            $status_text = _e('Active');
                            $status_class = 'dot-status-success';

                            if ($one->deleted) {
                                $status_text = _e('Deleted');
                                $status_class = 'dot-status-danger';
                            } elseif ($one->status == 0) {
                                $status_text = _e('Inactive');
                                $status_class = 'dot-status-warning';
                            }

                            if ($one->info) {
                                $info = $one->info;
                            } else {
                                $info = DirectionInfo::find()
                                    ->where(['direction_id' => $one->id])
                                    ->one();
                            }

                            $edit_url = $main_url . "/edit/?id={$one->id}";
                            $created_on = date_create($one->created_on); ?>
                            <tr>
                                <td class="ta-select-icon">
                                    <i class="ri-checkbox-blank-line" data-ta-select="<?= $one->id ?>"></i>
                                </td>
                                <td>
                                    <a href="<?= $edit_url; ?>" class="products-table-title " title="<?= $info->name ?>">
                                        <?= $info->name ? $info->name : '-'; ?>
                                    </a>
                                    <nav class="nav products-table-nav">
                                        
                                        <li class="text-secondary align-items-center" title="<?= _e('Created date'); ?>">
                                            <i class="ri-calendar-2-line mr-1"></i><?= date_format($created_on, 'd/m/y H:i'); ?>
                                        </li>
                                    </nav>
                                </td>
                                <td>
                                    <?= $one->hoursText ?>
                                </td>
                                <td class="text-center">
                                    <span class="<?= $status_class; ?>" data-toggle="tooltip" data-placement="bottom" title="<?= $status_text; ?>"></span>
                                </td>
                                <td class="ta-icons-block">
                                    <?php if ($one->status == 1) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="unpublish" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-eye-off-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Inactivate'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php elseif ($one->status == 0) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="publish" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-checkbox-circle-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Activate'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($one->deleted) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="restore" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-refresh-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Restore'); ?>"></i>
                                            </a>
                                        </div>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="delete" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-delete-bin-2-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Delete permanently'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php else : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="trash" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-delete-bin-6-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Move to trash'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <tr>
                            <td colspan="5" class="text-center table-not-found">
                                <i class="ri-error-warning-line"></i>
                                <div class="h5">
                                    <?= _e('Subjects not found'); ?>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<nav>
    <?php echo LinkPager::widget([
        'pagination' => $pagination,
        'options' => ['class' => 'pagination pagination-rounded'],
        'linkContainerOptions' => ['class' => 'page-item'],
        'linkOptions' => ['class' => 'page-link'],
        'prevPageLabel' => '<i class="ri-arrow-left-s-line"></i>',
        'nextPageLabel' => '<i class="ri-arrow-right-s-line"></i>',
        'disabledListItemSubTagOptions' => ['tag' => 'a', 'class' => 'page-link'],
    ]); ?>
</nav>

backend/views/education/subjects/update.php
<?php
$controller = Yii::$app->controller;
$lexicon = array_value($controller->settings, 'lexicon');

$this->title = _e('Edit subject');
$this->page_title =  _e('Edit subject');

$this->breadcrumb_title = _e('Edit subject');
$this->breadcrumbs[] = ['label' => _e('Subjects'), 'url' => $main_url]; ?>

<div class="Page-update">
<?= $this->render('_form', [
        'main_url' => $main_url,
        'model' => $model,
        'info' => $info
    ]); ?>
</div>