backend/models/Department.php
<?php

namespace backend\models;

use base\libs\Translit;
use common\models\DepartmentInfo;
use common\models\Department as CommonDepartment;
use common\models\LogsAdmin;
use common\models\LogsFrontend;

/**
 * Department model
 */
class Department extends CommonDepartment
{
    public static $type;
    public static $items_with_parent = false;

    /**
     * Get items
     *
     * @param string $page_type
     * @return object
     */
    public static function getItems($page_type = '', $args = array())
    {
        $search = input_get('s');
        $sort = input_get('sort');
        $parent = input_get('department');
        $type = input_get('type');

        $admin_current_lang = admin_current_lang();

        self::$selected_language = array_value($admin_current_lang, 'lang_code', 'en');

        if (empty($sort) && array_value($args, 'sort')) {
            $sort = array_value($args, 'sort');
        }

        if (empty($parent) && array_value($args, 'parent')) {
            $parent = array_value($args, 'parent');
        }

        if (empty($type) && array_value($args, 'type')) {
            $type = array_value($args, 'type');
        }

        $query = self::find()
            ->with('childs')
            ->join('INNER JOIN', 'department_info info', 'info.department_id = department.id');

        $query->andWhere(['language' => self::$selected_language]);

        if (is_numeric($parent) && $parent > 0) {
            $query->andWhere(['department.parent_id' => $parent]);
        }

        if (is_numeric($type) && $type > 0) {
            $query->andWhere(['department.type' => $type]);
        }


        if ($search) {
            $query->andWhere(['like', 'info.name', $search]);
        } 
        

        if ($sort == 'a-z') {
            $sort_query = ['info.name' => SORT_ASC];
        } elseif ($sort == 'z-a') {
            $sort_query = ['info.name' => SORT_DESC];
        } elseif ($sort == 'oldest') {
            $sort_query = ['department.created_on' => SORT_ASC];
        } else {
            $sort_query = ['department.created_on' => SORT_DESC];
        }

        

        $query->orderBy($sort_query);
        // rawsql($query);
        return $query;
    }

    /**
     * Page types
     *
     * @param string $active_key
     * @return array
     */
    public static function getPageTypes($active_key = '')
    {
        $page_types = array(
            'index' => array(
                'name' => _e('All'),
                'active' => false,
                'count' => self::itemsCount(['department.deleted' => 0]),
            ),
            'published' => array(
                'name' => _e('Published'),
                'active' => false,
                'count' => self::itemsCount(['department.deleted' => 0, 'department.status' => 1]),
            ),
            'unpublished' => array(
                'name' => _e('Unpublished'),
                'active' => false,
                'count' => self::itemsCount(['department.deleted' => 0, 'department.status' => 0]),
            ),
            'deleted' => array(
                'name' => _e('Deleted'),
                'active' => false,
                'count' => self::itemsCount(['department.deleted' => 1]),
            ),
        );

        if (isset($page_types[$active_key])) {
            $page_types[$active_key]['active'] = true;
        }

        return $page_types;
    }



    /**
     * Create item
     *
     * @param [type] $model
     * @param [type] $info
     * @param [type] $post_item
     * @return int
     */
    public static function createItem($model, $info, $post_item = array())
    {
        $log_data = array();
        $now_date = date('Y-m-d H:i:s');
        $current_user_id = current_user_id();
        $active_languages = admin_active_langs();

        // Create model
        $model->created_on = $now_date;
        $model->created_by = $current_user_id;
        $model->updated_on = $now_date;
        $model->updated_by = $current_user_id;

        if ($model->save()) {
            $log_data['department']['attrs'] = $model->getAttributes();
            $log_data['department']['old_attrs'] = array();

            // Create translations
            if ($active_languages) {

                foreach ($active_languages as $active_language) {

                    $lang_code = $active_language['lang_code'];

                    $new = new DepartmentInfo();
                    $new->department_id = $model->id;
                    $new->language = $lang_code;
                    $new->name = $info->name[$lang_code];
                    $new->description = $info->description[$lang_code];

                    if ($new->save()) {
                        $log_data['department_info'][$new->language]['attrs'] = $new->getAttributes();
                        $log_data['department_info'][$new->language]['old_attrs'] = array();
                    }else{
                        dd($new->errors);
                    }
                }
            }

            // Count childs
            //self::countChilds($model->parent_id);

            // Set log
            set_log('admin', [
                'res_id' => $model->id,
                'type' => 'department',
                'action' => 'create',
                'data' => json_encode($log_data),
            ]);

        }else{
            dd($model->errors);
        }

        return $model->id;
    }

    /**
     * Update item
     *
     * @param [type] $model
     * @param [type] $info
     * @param [type] $post_item
     * @return int
     */
    public static function updateItem($model, $info, $post_item = array())
    {
        $log_data = array();
        $now_date = date('Y-m-d H:i:s');
        $active_languages = admin_active_langs();
        $old_parent_id = $model->getOldAttribute('parent_id');
        $current_user_id = current_user_id();

        // Save model
        $model->updated_on = $now_date;
        $model->updated_by = $current_user_id;

        $modelOldAttributes = $model->getOldAttributes();

        if ($model->save()) {
            $log_data['department']['attrs'] = $model->getAttributes();
            $log_data['department']['old_attrs'] = $modelOldAttributes;

            // Create translations
            if ($active_languages) {

                foreach ($active_languages as $active_language) {

                    $lang_code = $active_language['lang_code'];

                    $infoSingleLang = DepartmentInfo::find()->where(['department_id' => $model->id, 'language' => $lang_code])->one();
                    if($infoSingleLang){
                        $infoSingleLang->name = $info->name[$lang_code];
                        $infoSingleLang->description = $info->description[$lang_code];

                        $infoOldAttributes = $infoSingleLang->getOldAttributes();

                        if ($infoSingleLang->save()) {
                            $log_data['department_info'][$infoSingleLang->language]['attrs'] = $infoSingleLang->getAttributes();
                            $log_data['department_info'][$infoSingleLang->language]['old_attrs'] = $infoOldAttributes;
                        }else{
                            dd($infoSingleLang->errors);
                        }
                    }
                    
                }
            }

            // Count childs
            //self::countChilds($model->parent_id);
            //self::countChilds($old_parent_id);

            // Set log
            set_log('admin', [
                'res_id' => $model->id,
                'type' => 'department',
                'action' => 'update',
                'data' => json_encode($log_data),
            ]);
        }else{
            dd($model->errors);
        }

        return $model->id;
    }

    /**
     * Get item to edit
     *
     * @param int $id
     * @return array
     */
    public static function getItemToEdit($id)
    {
        $current_language = admin_current_lang();
        $lang_code = array_value($current_language, 'lang_code', 'en');

        $model = self::findOne($id);
        $info = new DepartmentInfo();
        $translations = DepartmentInfo::find()->where(['department_id' => $id])->all();
        $names = [];
        $descriptions = [];
        foreach ($translations as $translation) {
            $names[$translation['language']] = $translation['name'];
            $descriptions[$translation['language']] = $translation['description'];
        }

        $info->name = $names;
        $info->description = $descriptions;

        $output['model'] = $model;
        $output['info'] = $info;
        $output['translations'] = $translations;

        return $output;
    }

    /**
     * Get parents list
     *
     * @param [type] $model
     * @param [type] $info
     * @param [type] $parent_id
     * @param [type] $type
     * @return array
     */
    public static function getListParent($model, $info, $parent_id = 0, $type = '')
    {
        if ($model == 'product') {
            if ($type == 'category') {
                $output = array('' => _e('No category'));
            } elseif ($type == 'brand') {
                $output = array('0' => _e('No brand'));
            } else {
                $output = array('' => '-');
            }

            $where = array('department.type' => $type);
        } else {
            $output = array('0' => _e('No parent'));
            $where = array('department.type' => self::$type);
        }

        if (isset($info->language) && $info->language) {
            self::$selected_language = $info->language;
        }

        if (is_numeric($parent_id) && $parent_id > 0) {
            $where['department.parent_id'] = $parent_id;
        } else {
            $where['department.parent_id'] = 0;
        }

        $query = self::find()
            ->alias('content')
            ->select('department.*, info.name as default_title')

common/models/Department.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "department".
 *
 * @property int $id
 * @property string $type
 * @property int|null $parent_id
 * @property int $sort
 * @property int|null $status
 * @property int $deleted
 * @property string|null $created_on
 * @property int $created_by
 * @property string|null $updated_on
 * @property int $updated_by
 */
class Department extends \base\libs\RedisDB
{

    public static $selected_language = 'en';

    const TYPE_DIVISION = 1;
    const TYPE_DEANERY = 2;
    const TYPE_CHAIR = 3;
    const TYPE_CENTER = 4;
    const TYPE_RECTORATE = 5;

    /**
     * Table name
     *
     * @return string
     */
    public static function tableName()
    {
        return 'department';
    }

    /**
     * Rules
     *
     * @return array
     */
    public function rules()
    {
        return [
            [['sort','type'], 'required'],
            [['created_on', 'updated_by'], 'safe'],
            [['parent_id', 'sort', 'status', 'deleted', 'created_by', 'updated_by'], 'integer'],
            [['parent_id', 'status', 'sort', 'deleted'], 'default', 'value' => 0],
            ['created_on', 'default', 'value' => date('Y-m-d H:i:s')],
            ['updated_on', 'default', 'value' => date('Y-m-d H:i:s')],
        ];
    }

    /**
     * Attribute labels
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => _e('ID'),
            'type' => _e('Type'),
            'parent_id' => _e('Parent'),
            'sort' => _e('Sort'),
            'status' => _e('Status'),
            'deleted' => _e('Deleted'),
            'created_on' => _e('Created on'),
            'created_by' => _e('Created by'),
            'updated_on' => _e('Updated on'),
            'updated_by' => _e('Updated by'),
        ];
    }

    /**
     * Get content infos
     *
     * @return void
     */
    public function getInfos()
    {
        return $this->hasMany(DepartmentInfo::class, ['department_id' => 'id']);
    }

    /**
     * Get childs
     *
     * @return void
     */
    public function getChilds()
    {
        return $this->hasMany(Department::class, ['parent_id' => 'id']);
    }

    /**
     * Get content info
     *
     * @return void
     */
    public function getInfoRelation()
    {
        self::$selected_language = array_value(admin_current_lang(), 'lang_code', 'en');
        return $this->hasMany(DepartmentInfo::class, ['department_id' => 'id'])
                    ->andOnCondition(['language' => self::$selected_language]);
    }

    /**
     * Get info
     *
     * @return void
     */
    public function getInfo()
    {
        return $this->infoRelation[0];
    }
    
    /**
     * Get parent
     *
     * @return void
     */
    public function getParent()
    {
        return $this->hasOne(self::className(), ['id' => 'parent_id']);
    }

    /**
     * Get created by
     *
     * @return void
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * Get created by
     *
     * @return void
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }

    /**
     * Get parent
     *
     * @return void
     */
    public function getParentInfoRelation()
    {
        return $this->hasOne(DepartmentInfo::class, ['department_id' => 'id'])
            ->via('parent')
            ->andOnCondition(['language' => self::$selected_language]);
    }

    /**
     * Get parent
     *
     * @return void
     */
    public function getParentInfo()
    {
        return $this->parentInfoRelation[0];
    }

    public static function listTypes($lang = null){
        $lang = $lang ?? self::$selected_language;
        return [
            self::TYPE_DIVISION => _t('app', 'Division',[],$lang),
            self::TYPE_DEANERY => _t('app', 'Deanery',[],$lang),
            self::TYPE_CHAIR => _t('app', 'Chair',[],$lang),
            self::TYPE_CENTER => _t('app', 'Center',[],$lang),
            self::TYPE_RECTORATE => _t('app', 'Rectorate',[],$lang)
        ];
    }

    public function getTypeText(){
        self::$selected_language = Yii::$app->request->get('lang') ?? 'en';
        return self::listTypes(self::$selected_language)[$this->type];
    }

    public static function listOtherDepartments($department_id = null, $lang = null){
        
        $lang = $lang ?? self::$selected_language;
        $result = self::find()
            ->join('INNER JOIN', 'department_info info', 'info.department_id = department.id')
            ->select('department.*, info.*')
            ->where(['info.language' => $lang])
            ->andFilterWhere(['<>','id',$department_id])
            ->asArray()->all();
        $list = [];
        foreach ($result as $one) {
            $list[$one['id']] = $one['name'];
        }
        return $list;
    }

    public static function listAll($type = null, $lang = null){
        
        $lang = $lang ?? self::$selected_language;
        $typeCondition = ($type) ? ['type' => $type] : [];
        $result = self::find()
            ->join('INNER JOIN', 'department_info info', 'info.department_id = department.id')
            ->select('department.*, info.*')
            ->where([
                'and',
                ['info.language' => $lang],
                $typeCondition
            ])
            ->asArray()->all();
        $list = [];
        foreach ($result as $one) {
            $list[$one['id']] = $one['name'];
        }
        return $list;
    }

    /**
     * Status array
     *
     * @param int $key
     * @return array
     */
    public function statusArray($key = null)
    {
        $array = [
            1 => _e('Active'),
            0 => _e('Inactive'),
        ];

        if (isset($array[$key])) {
            return $array[$key];
        }

        return $array;
    }

    /**
     * Redis db relationship
     *
     * @return mixed
     */
    public function redisDbRelationship() {
        return array(new Department(), new  DepartmentInfo());
    }

}

backend/views/hr/departments/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

$languages = admin_active_langs();
$langs_array = ArrayHelper::map($languages, 'lang_code', 'name');
$content_language = admin_content_lexicon('lang_code');

if ($model->isNewRecord) {
    $model->sort = 0;
    $model->created_by = Yii::$app->user->id;
    $model->updated_by = Yii::$app->user->id;
    $info->language = $content_language;
}

// Languages
$lang = input_get('lang');

if (is_string($lang) && $lang) {
    $info->language = $lang;
}

// Parent id
$parent_id = input_get('parent');

if (is_numeric($parent_id) && $parent_id > 0) {
    $model->parent_id = $parent_id;
}

// dd($info);

// Begin form
$form = ActiveForm::begin([
    'options' => [
        'class' => 'full-form',
    ],
]); ?>



<div class="row">
    <!-- Left column -->
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                
                <!-- Nav tabs -->
                <ul class="nav nav-tabs nav-tabs-custom nav-justified mb-3" role="tablist">
                    <?php foreach($languages as $lang){?>
                        <li class="nav-item">
                            <a class="nav-link <?php if($content_language == $lang['lang_code']) echo "active"?>" data-toggle="tab" href="#tab_<?=$lang['lang_code']?>" role="tab">
                                <span class="d-none d-sm-block">
                                    <img src="<?= $lang['flag']; ?>" alt="<?= $lang['lang_code']; ?>" height="10" width="17">
                                    <?=$lang['name']?>
                                </span>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
                <!-- /Nav tabs -->

                <div class="tab-content">
                    <?php foreach($languages as $lang){?>
                        <!-- Tab item -->
                        <div class="tab-pane <?php if($content_language == $lang['lang_code']) echo "active"?>" id="tab_<?=$lang['lang_code']?>" role="tabpanel">
                            
                            <?= $form->field($info, 'name['.$lang['lang_code'].']')->textInput(['ep-bind-action' => 'title']) ?>
                            <?= $form->field($info, 'description['.$lang['lang_code'].']')->textarea() ?>
                        
                        </div>
                        <!-- /Tab item -->
                    <?php } ?>
                
                </div>
                
                
                

            </div>
        </div>



    </div>
    <!-- /Left column -->

    <!-- Right column -->
    <div class="col-md-3">

        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <?= html_entity_decode($form->field($model, 'parent_id')->dropDownList(
                        $listOtherDepartments,
                        [
                            'prompt' => _e('No parent'),
                            'class' => 'form-control select2',
                        ]
                    )) ?>
                </div>

                <div class="form-group required-field">
                    <?= html_entity_decode($form->field($model, 'type')->dropDownList(
                        $listTypes,
                        [
                            'class' => 'form-control select2',
                            'required' => 'required',
                        ]
                    )) ?>
                </div>

                <div class="form-group required-field">
                    <?= $form->field($model, 'status')->dropDownList($model->statusArray(), ['class' => 'form-control custom-select', 'required' => 'required']) ?>
                </div>

                <div class="form-group required-field">
                    <?= $form->field($model, 'sort')->textInput(['type' => 'number', 'required' => 'required']) ?>
                </div>
            </div>
        </div>

    </div>
    <!-- /Right column -->
</div>

<div class="mb-3 full-form-btns">
    <?php
    if ($model->isNewRecord) {
        echo Html::submitButton('<i class="ri-check-line mr-1"></i> ' . _e('Create'), ['class' => 'btn btn-success waves-effect btn-with-icon']);
        echo Html::submitButton('<i class="ri-add-circle-line mr-1"></i> ' . _e('Create & add another'), ['class' => 'btn btn-primary waves-effect btn-with-icon', 'name' => 'submit_button', 'value' => 'create_and_add_new']);
    } else {
        echo Html::submitButton('<i class="ri-check-line mr-1"></i> ' . _e('Save'), ['class' => 'btn btn-success waves-effect btn-with-icon']);
        echo Html::submitButton('<i class="ri-add-fill mr-1"></i> ' . _e('Save & add another'), ['class' => 'btn btn-primary waves-effect btn-with-icon', 'name' => 'submit_button', 'value' => 'create_and_add_new']);
    } ?>
</div>
<?php ActiveForm::end(); ?>

backend/views/hr/departments/create.php
<?php
$controller = Yii::$app->controller;

$this->title = _e('Create department');
$this->page_title = $this->title;
$this->breadcrumbs[] = ['label' => _e('Departments'), 'url' => $main_url]; ?>

<div class="Page-create">
    <?= $this->render('_form', [
        'main_url' => $main_url,
        'model' => $model,
        'info' => $info,
        'listTypes' => $listTypes,
        'listOtherDepartments' => $listOtherDepartments
    ]); ?>
</div>

backend/views/hr/departments/page.php
<?php

use backend\widgets\BulkActions;
use common\models\DepartmentInfo;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$lexicon = admin_content_lexicon('lang_code');
$admin_current_lang = admin_current_lang('lang_code');

$controller = Yii::$app->controller;

$this->title = _e('Departments'); 
?>

<div class="card-top-links row">
    <div class="col-md-7">
        <div class="card-listed-links">
            <?php foreach ($page_types as $page_type_key => $page_type) : ?>
                <a href="<?= $main_url . '/' . $page_type_key; ?>" <?= $page_type['active'] ? 'class="active"' : ''; ?>>
                    <?= $page_type['name']; ?>
                    <span>(<?= $page_type['count']; ?>)</span>
                </a>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="col-md-5">
        <div class="card-listed-links-right">
            <a href="<?= $main_url; ?>/create" class="btn btn-info waves-effect">
                <?= _e('Add new') ?>
            </a>
            <a href="<?= admin_url(); ?>" class="btn btn-secondary waves-effect">
                <?= _e('Close') ?>
            </a>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="card-body-top">

            <?= BulkActions::widget(array(
                'actions' => $bulk_actions,
                'limit_default' => $limit_default,
                'sort_default' => $sort_default,
                'departments' => $listAll,
                'departmentTypes' => $listTypes
            )); ?>
        </div>

        <div class="table-responsive table-with-actions">
            <input type="hidden" id="table-selected-items" ta-selected-items>

            <table class="table mb-0">
                <thead class="thead-light">
                    <tr>
                        <th width="30px" class="ta-select-icon">
                            <i class="ri-checkbox-blank-line" data-ta-select-all></i>
                        </th>
                        <th><?= _e('Name') ?></th>
                        <th><?= _e('Type'); ?></th>
                        <th><?= _e('Parent'); ?></th>
                        <th class="text-center" width="80px"><?= _e('Status'); ?></th>
                        <th width="180px"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($content) : ?>
                        <?php foreach ($content as $key => $one) : ?>
                            <?php
                            $status_text = _e('Active');
                            $status_class = 'dot-status-success';

                            if ($one->deleted) {
                                $status_text = _e('Deleted');
                                $status_class = 'dot-status-danger';
                            } elseif ($one->status == 0) {
                                $status_text = _e('Inactive');
                                $status_class = 'dot-status-warning';
                            }

                            if ($one->info) {
                                $info = $one->info;
                            } else {
                                $info = DepartmentInfo::find()
                                    ->where(['department_id' => $one->id])
                                    ->one();
                            }

                            $edit_url = $main_url . "/edit/?id={$one->id}";
                            $created_on = date_create($one->created_on); ?>
                            <tr>
                                <td class="ta-select-icon">
                                    <i class="ri-checkbox-blank-line" data-ta-select="<?= $one->id ?>"></i>
                                </td>
                                <td>
                                    <a href="<?= $edit_url; ?>" class="products-table-title " title="<?= $info->name ?>">
                                        <?= $info->name ? $info->name : '-'; ?>
                                    </a>
                                    <nav class="nav products-table-nav">
                                        
                                        <li class="text-secondary align-items-center">
                                            <?= _e('Child items'); ?>: <?= count($one->childs); ?>
                                        </li>
                                        
                                        <li class="text-secondary align-items-center" title="<?= _e('Created date'); ?>">
                                            <i class="ri-calendar-2-line mr-1"></i><?= date_format($created_on, 'd/m/y H:i'); ?>
                                        </li>
                                    </nav>
                                </td>
                                <td>
                                    <?= $one->typeText ?>
                                </td>
                                <td>
                                    <?= ($one->parent_id) ? $one->parent->info->name : '-' ?>
                                </td>
                                <td class="text-center">
                                    <span class="<?= $status_class; ?>" data-toggle="tooltip" data-placement="bottom" title="<?= $status_text; ?>"></span>
                                </td>
                                <td class="ta-icons-block">
                                    
                                    <div class="ta-icons-in">
                                        <a href="<?= $main_url; ?>/create/?parent=<?= $one->id ?>">
                                            <i class="ri-add-circle-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Add child page'); ?>"></i>
                                        </a>
                                    </div>
                                    <div class="ta-icons-in">
                                        <a href="<?= set_query_var('parent', $one->id); ?>">
                                            <i class="ri-list-unordered" data-toggle="tooltip" data-placement="top" title="<?= _e('Child pages'); ?>"></i>
                                        </a>
                                    </div>
                                    <?php if ($one->status == 1) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="unpublish" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-eye-off-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Inactivate'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php elseif ($one->status == 0) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="publish" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-checkbox-circle-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Activate'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($one->deleted) : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="restore" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-refresh-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Restore'); ?>"></i>
                                            </a>
                                        </div>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="delete" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-delete-bin-2-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Delete permanently'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php else : ?>
                                        <div class="ta-icons-in">
                                            <a href="javascript:void(0);" ta-single-action="trash" ta-single-id="<?= $one->id ?>">
                                                <i class="ri-delete-bin-6-line" data-toggle="tooltip" data-placement="top" title="<?= _e('Move to trash'); ?>"></i>
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <tr>
                            <td colspan="5" class="text-center table-not-found">
                                <i class="ri-error-warning-line"></i>
                                <div class="h5">
                                    <?= _e('Departments not found'); ?>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<nav>
    <?php echo LinkPager::widget([
        'pagination' => $pagination,
        'options' => ['class' => 'pagination pagination-rounded'],
        'linkContainerOptions' => ['class' => 'page-item'],
        'linkOptions' => ['class' => 'page-link'],
        'prevPageLabel' => '<i class="ri-arrow-left-s-line"></i>',
        'nextPageLabel' => '<i class="ri-arrow-right-s-line"></i>',
        'disabledListItemSubTagOptions' => ['tag' => 'a', 'class' => 'page-link'],
    ]); ?>
</nav>