common/models/Student.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "student".
 *
 * @property int $id
 * @property int|null $user_id
 * @property int|null $department_id
 * @property int|null $education_direction_id
 * @property int|null $basis_of_learning
 * @property int|null $education_type
 * @property string|null $diploma_number
 * @property string|null $diploma_date
 * @property int|null $type_of_residence
 * @property string|null $landlord_info
 * @property string|null $student_live_with
 * @property string|null $other_info
 */
class Student extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'student';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'department_id', 'gender', 'education_direction_id', 'basis_of_learning', 'education_type', 'type_of_residence'], 'integer'],
            [['diploma_date'], 'safe'],
            [['landlord_info', 'student_live_with', 'other_info'], 'string'],
            [['diploma_number'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {

        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User'),
            'department_id' => Yii::t('app', 'Department'),
            'education_direction_id' => Yii::t('app', 'Education speciality'),
            'basis_of_learning' => _e('Basis of learning'),
            'education_type' => Yii::t('app', 'Education type'),
            'diploma_number' => _e('Diploma number'),
            'diploma_date' => _e('Date of issue of the diploma'),
            'type_of_residence' => _e('Type of residence'),
            'landlord_info' => Yii::t('app', 'Landlord info'),
            'student_live_with' => Yii::t('app', 'Student live with'),
            'other_info' => Yii::t('app', 'Other informations (student)'),
        ];
    }

    public function getDepartment()
    {
        return $this->hasOne(Department::class, ['id' => 'department_id']);
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use yii\helpers\Url;
use yii\data\Pagination;
use backend\models\User;
use base\BackendController;
use common\models\Department;
use common\models\EducationWork;
use common\models\Employee;
use common\models\Profile;
use common\models\Reference;
use common\models\Subject;
use common\models\UserSubject;
/**
 * User controller
 */
class UsersController extends BackendController
{
    use ListActionsTrait;

    public $url = '/users';

    /**
     * Displays user subject page
     *
     * @return string
     */
    public function actionSubjects()
    {
        $main_url = Url::to([$this->url]);
        $where = ['users.deleted' => 0, 'users.status' => 10];
        $limit_default = 20;
        $sort_default = 'a-z';

        $limit = input_get('limit', $limit_default);

        $args = ['sort' => $sort_default];
        $query = User::getItems('', $args)->andWhere($where);
        $count = $query->count();

        if (!empty($limit)) {
            $pagination = new Pagination(['totalCount' => $count, 'pageSize' => $limit]);
        } else {
            $pagination = new Pagination(['totalCount' => $count]);
        }

        $users = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        $listDepartments = Department::listAll(null, $this->selected_language);
        $subjects = Subject::listAll($this->selected_language);
        $languages = Reference::listAll('language',$this->selected_language);

        return $this->render('subjects', array(
            'main_url' => $main_url,
            'limit_default' => $limit_default,
            'sort_default' => $sort_default,
            'users' => $users,
            'pagination' => $pagination,
            'listDepartments' => $listDepartments,
            'subjects' => $subjects,
            'languages' => $languages,
        ));

    }

    /**
     * Displays subject binding page
     *
     * @return string
     */
    public function actionBindsubject($id)
    {
        $model = User::findOne($id);
        $profile = Profile::find()->with(['permanentPlace.parent'])->where(['user_id' => $id])->one();
        $employee = Employee::find()->where(['user_id' => $id])->one();
        $main_url = Url::to([$this->url]);
        $post_item = Yii::$app->request->post();

        if (!$model || !$profile) {
            return $this->render('error', array(
                'main_url' => $main_url,
            ));
        }

        if ($post_item) {
            $data = json_decode($post_item['data']);
            
            if (is_array($data)) {
                $readyData = [];
                
                foreach ($data as $row) {
                    if (!$row->subject) {
                        continue;
                    }
                    foreach ($row->langs as $lang) {
                        if (!$lang) {
                            continue;
                        }
                        $readyData[] =  $row->subject . ',' . $lang;
                    }
                }
                $readyData = array_unique($readyData);
                
                // if (!empty($readyData)) {
                    $transaction = Yii::$app->db->beginTransaction();
                    $error = false;

                    UserSubject::deleteAll(['user_id' => $id]);

                    foreach ($readyData as $row) {
                        list($subject, $lang) = explode(',', $row);
                        $userSubject = new UserSubject();
                        $userSubject->user_id = $id;
                        $userSubject->subject_id = $subject;
                        $userSubject->language_id = $lang;
                        if (!$userSubject->save()) {
                            $error = true;
                            dd($userSubject->errors);
                        }
                    }
                        

                    if ($error) {
                        $transaction->rollBack();
                    } else {
                        $transaction->commit();
                    }
                // }
            }


            return $this->refresh();
        }

        $this->registerJs(array(
            'dist/libs/tinymce/tinymce.min.js',
            'theme/components/tinymce-editor.js',
            'js/custom.js',
        ));

        $subjects = Subject::listAll($this->selected_language);
        $languages = Reference::listAll('language',$this->selected_language);

        return $this->render('bind-subject', [
            'main_url' => $main_url,
            'model' => $model,
            'profile' => $profile,
            'employee' => $employee,
            'subjects' => $subjects,
            'languages' => $languages,
            'userSubjects' => $model->userSubjects,
        ]);
    }

    /**
     * Page
     *
     * @param string $type
     * @param array $where_query
     * @param array $bulk_actions
     * @param array $where_in
     * @return void
     */
    private function page($type, $where_query, $bulk_actions, $where_in = array())
    {
        $main_url = Url::to([$this->url]);

        $limit_default = 20;
        $sort_default = 'a-z';

        $ajax = input_post('ajax');
        $limit = input_get('limit', $limit_default);

        $args = ['sort' => $sort_default];
        $query = User::getItems($type, $args)->andWhere($where_query);

        if (is_array($where_in) && $where_in) {
            $query->andWhere($where_in);
        }

        $count = $query->count();

        if ($ajax == 'bulk-actions') {
            $ajax_action = input_post('action');
            $ajax_items = input_post('items');
            $ajax_item_id = input_post('id');
            $items = explode(',', $ajax_items);

            $output = User::ajaxAction($ajax_action, $ajax_item_id, $items);

            echo json_encode($output);
            exit();
        }

        if (!empty($limit)) {
            $pagination = new Pagination(['totalCount' => $count, 'pageSize' => $limit]);
        } else {
            $pagination = new Pagination(['totalCount' => $count]);
        }

        $users = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        $page_types = User::getPageTypes($type);

        return $this->render('index', array(
            'main_url' => $main_url,
            'page_types' => $page_types,
            'bulk_actions' => $bulk_actions,
            'limit_default' => $limit_default,
            'sort_default' => $sort_default,
            'users' => $users,
            'pagination' => $pagination,
        ));
    }

    /**
     * Displays create page
     *
     * @return string
     */
    public function actionCreate($id = null)
    {
        $model = new User();
        $profile = new Profile();
        $main_url = Url::to([$this->url]);
        $post_item = Yii::$app->request->post();

        if($id){

            $modelCopy = User::findOne($id);
            $profileCopy = Profile::find()->where(['user_id' => $id])->one();

            if (!$modelCopy || !$profileCopy) {
                return $this->render('error', [
                    'error_info' => [
                        'title' => _e('Not found'),
                        'text' => _e('User not found!'),
                        'desc' => _e('The user you were looking for does not exist, unavailable for you or deleted.'),
                    ],
                    'main_url' => $main_url,
                ]);
            }

            $model->setAttributes($modelCopy->getAttributes());
            $profile->setAttributes($profileCopy->getAttributes());

            $model->roleName = $modelCopy->role->item_name;

            $profile->dob = date('Y-m-d',strtotime($profile->dob));

        }

        if ($post_item) {

            $submit_button = input_post('submit_button');

            if ($submit_button == 'create_and_add_new' && $model->load($post_item) && $profile->load($post_item)) {
                
                $model->createUser($model, $profile);
                Yii::$app->session->setFlash('success-alert', _e("The user was created successfully."));
                return $this->redirect(['create']);

            } elseif ($model->load($post_item) && $profile->load($post_item)) {

                $user_id = $model->createUser($model, $profile);
                Yii::$app->session->setFlash('success-alert', _e("The user was created successfully."));
                return $this->redirect(['edit', 'id' => $user_id]);

            }
        }

        $this->registerJs(array(
            'dist/libs/tinymce/tinymce.min.js',
            'theme/components/tinymce-editor.js',
            'js/custom.js',
        ));

        return $this->render('create', [
            'main_url' => $main_url,
            'model' => $model,
            'profile' => $profile,
        ]);
    }

    /**
     * Displays edit page
     *
     * @return string
     */
    public function actionEdit($id)
    {
        $model = User::findOne($id);
        $profile = Profile::find()->with(['permanentPlace.parent'])->where(['user_id' => $id])->one();
        $main_url = Url::to([$this->url]);
        $post_item = Yii::$app->request->post();

        if (!$model || !$profile) {
            return $this->render('error', array(
                'main_url' => $main_url,
            ));
        }

        $model->roleName = $model->role->item_name;

        $profile->dob = date('Y-m-d',strtotime($profile->dob));

        if ($post_item) {
            $submit_button = input_post('submit_button');

            if ($submit_button == 'create_and_add_new' && $model->load($post_item) && $profile->load($post_item)) {
                $model->updateUser($model, $profile, $post_item);

                Yii::$app->session->setFlash('success-alert', _e("The user has been successfully updated."));

backend/views/users/_form.php
<?php

use common\models\enums\DisabilityGroup;
use common\models\enums\FamilyStatus;
use common\models\enums\Gender;
use common\models\enums\YesNo;
use backend\widgets\StorageWidget;
use common\models\AuthItem;
use common\models\UsersSession;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

if ($model->isNewRecord) {
    $lastSession = array();
} else {
    $lastSession = UsersSession::getLog($model->id, 'last_session');
}

// Begin form
$form = ActiveForm::begin([
    'options' => [
        'class' => 'full-form'
    ]
]);
?>


<!-- Nav tabs -->
<ul class="nav nav-tabs nav-tabs-custom nav-justified mb-3" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#general" role="tab">
            <span class=""><i class="far fa-user"></i></span>
            <span class="d-none d-sm-block"><?= _e('General'); ?></span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#profile" role="tab">
            <span class=""><i class="far fa-address-card"></i></span>
            <span class="d-none d-sm-block"><?= _e('Profile'); ?></span>
        </a>
    </li>
</ul>

<div class="tab-content">


    <!-- Tab item -->
    <div class="tab-pane active" id="general" role="tabpanel">
        <div class="row">

            <!-- Left column -->
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 form-group required-field">
                                <?= $form->field($model, 'username')->textInput(['maxlength' => true, 'required' => 'required']) ?>
                            </div>

                            <div class="col-md-6 form-group required-field">
                                <?= $form->field($model, 'email')->textInput(['type' => 'email', 'required' => 'required']) ?>
                            </div>

                            <div class="col-md-6 form-group required-field">
                                <?= $form->field($profile, 'firstname')->textInput(['required' => 'required']) ?>
                            </div>

                            <div class="col-md-6 form-group required-field">
                                <?= $form->field($profile, 'lastname')->textInput(['class' => 'form-control', 'required' => 'required']) ?>
                            </div>

                            <div class="col-md-6 form-group">
                                <?= $form->field($profile, 'middlename')->textInput([]) ?>
                            </div>
                            <div class="col-md-6 form-group">

                            </div>

                            <?php if ($model->isNewRecord) : ?>
                                <div class="col-md-6 form-group">
                                    <div class="form-group required-field">
                                        <?= $form->field($model, 'password')->passwordInput(['required' => 'required']) ?>
                                    </div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <div class="form-group required-field">
                                        <?= $form->field($model, 'password_repeat')->passwordInput(['required' => 'required']) ?>
                                    </div>
                                </div>
                            <?php else : ?>
                                <div class="col-md-6 form-group">
                                    <div class="form-group">
                                        <?= $form->field($model, 'password')->passwordInput() ?>
                                    </div>
                                </div>
                                <div class="col-md-6 form-group">
                                    <div class="form-group">
                                        <?= $form->field($model, 'password_repeat')->passwordInput() ?>
                                    </div>
                                </div>
                            <?php endif; ?>


                        </div>
                    </div>
                </div>
            </div>
            <!-- /Left column -->

            <!-- Right column -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 form-group">
                                <div class="form-group required-field">
                                    <?php
                                    $listdata = ArrayHelper::map(AuthItem::find()
                                        ->where(['type' => 1])
                                        ->all(), 'name', 'description');
                                    foreach ($listdata as $key => $row) {
                                        $listdata[$key] = _e($row);
                                    }

                                    echo $form->field($model, 'roleName')->dropDownList(
                                        $listdata,
                                        [
                                            'class' => 'form-control custom-select',
                                            'required' => 'required',
                                        ]
                                    ) ?>
                                </div>
                            </div>
                            <div class="col-md-12 form-group">
                                <div class="form-group required-field">
                                    <?= $form->field($model, 'status')->dropDownList([
                                        10 => _e('Active'),
                                        0 => _e('Pending'),
                                        5 => _e('Blocked'),
                                    ], [
                                        'class' => 'form-control custom-select',
                                        'required' => 'required',
                                    ]) ?>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">

                        <div class="form-group">
                            <label><?= _e('Register date'); ?></label>
                            <?php $created_at = $model->created_at > 0 ? date('d/m/Y H:i', $model->created_at) : '-'; ?>
                            <input type="text" class="form-control" value="<?= $created_at; ?>" disabled>
                        </div>
                        <div class="form-group">
                            <label><?= _e('Updated on'); ?></label>
                            <?php $updated_at = $model->updated_at > 0 ? date('d/m/Y H:i', $model->updated_at) : '-'; ?>
                            <input type="text" class="form-control" value="<?= $updated_at; ?>" disabled>
                        </div>
                        <div class="form-group">
                            <label for="last_login"><?= _e('Last login'); ?></label>
                            <input type="text" class="form-control" id="last_login" value="<?= $lastSession ? $lastSession->date : ''; ?>" disabled>
                        </div>
                        <div class="form-group">
                            <label for="last_ip"><?= _e('Last IP address'); ?></label>
                            <input type="text" class="form-control" id="last_ip" value="<?= $lastSession ? $lastSession->ip_address : ''; ?>" disabled>
                        </div>
                        <div class="form-group">
                            <label for="last_session"><?= _e('Last session'); ?></label>
                            <input type="text" class="form-control" id="last_session" value="<?= $lastSession ? $lastSession->session : ''; ?>" disabled>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Right column -->

        </div>
    </div>
    <!-- /Tab item -->

    <!-- Tab item -->
    <div class="tab-pane" id="profile" role="tabpanel">
        <div class="row">
            <!-- Left column -->
            <div class="col-md-12">

                <div class="card">
                    <div class="card-body">
                        <div class="form-group position-relative">
                            <?php
                            $form_template = StorageWidget::widget([
                                'format' => 'form',
                                'select_type' => 'single',
                                'action' => 'image_action',
                            ]);

                            echo $form->field($profile, 'image', ['template' => $form_template])
                                ->textInput(['type' => 'hidden', 'storage-browser-value' => 'image']) ?>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 form-group required-field">
                                <?= $form->field($profile, 'gender')->dropDownList(Gender::list(), [
                                    'class' => 'form-control',
                                    'prompt' => _e('...')
                                ]) ?>
                            </div>

                            <div class="col-md-3 form-group">
                                <?= $form->field($profile, 'phone')->textInput(['class' => 'form-control']) ?>
                            </div>

                            <div class="col-md-3 form-group">
                                <?= $form->field($profile, 'phone_secondary')->textInput(['class' => 'form-control']) ?>
                            </div>

                            <div class="col-md-3 form-group">
                                <?= $form->field($profile, 'dob')->textInput(['class' => 'form-control', 'type' => 'date']) ?>
                            </div>

                        </div>
                    </div>
                </div>
                
            </div>
            <!-- /Left column -->

        </div>
    </div>
    <!-- /Tab item -->

</div>


<div class="mb-3 full-form-btns">
    <?php
    if ($model->isNewRecord) {
        echo Html::submitButton('<i class="ri-check-line mr-1"></i> ' . _t('app', 'Create & open'), ['class' => 'btn btn-success waves-effect btn-with-icon']);
        echo Html::submitButton('<i class="ri-add-circle-line mr-1"></i> ' . _t('app', 'Create & add another'), ['class' => 'btn btn-primary waves-effect btn-with-icon', 'name' => 'submit_button', 'value' => 'create_and_add_new']);
    } else {
        echo Html::submitButton('<i class="ri-check-line mr-1"></i> ' . _t('app', 'Save'), ['class' => 'btn btn-success waves-effect btn-with-icon']);
        echo Html::submitButton('<i class="ri-add-fill mr-1"></i> ' . _t('app', 'Save & add another'), ['class' => 'btn btn-primary waves-effect btn-with-icon', 'name' => 'submit_button', 'value' => 'create_and_add_new']);
    } ?>
</div>
<?php ActiveForm::end(); ?>

backend/views/users/bind-subject.php
<?php

use common\models\Profile;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = _e('Attaching subject to teacher');
$this->breadcrumb_title = $this->title;
$this->breadcrumbs[] = ['label' => _e('Teacher subjects'), 'url' => $main_url . '/subjects'];

$form = ActiveForm::begin([
    'options' => [
        'class' => 'full-form'
    ]
]);

?>

<div class="user-bind-subject">
    <div class="card">
        <div class="row no-gutters">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title" style="font-size: 24px;"><?= Profile::getFullname($profile) ?></h5>
                    <p class="card-text" style="font-size: 16px;">
                        <?= _e('Department')?>: <b><?= $employee->department->info->name ?? '-'?></b>
                        <br>
                        <?= _e('Job')?>: <b><?= $employee->job->info->name ?? '-'?></b>                        
                    </p>
                </div>
            </div>
            <div class="col-md-4 text-right">
                <img class="card-img img-fluid" style="width: 145px;" src="<?= Profile::getAvatar($profile) ?>" alt="<?= Profile::getFullname($profile) ?>">
            </div>

        </div>
    </div>
    <div class="card">
        <div class="card-body">

            <div class="dropdown float-right">
                <div class="btn btn-primary btn-sm btn-add-option">
                    <i class="mdi mdi-plus"></i> <?= _e('Add subject') ?>
                </div>

            </div>

            <h4 class="card-title"><?= _e('Subjects') ?></h4>
            <p class="card-title-desc"><?= _e('You can select one or more subjects and languages for this teacher') ?></p>

            <div class="table-responsive">
                <table class="table mb-0" id="tbl-subjects">

                    <thead class="table-light">
                        <tr>
                            <th style="width: 20%;"><?= _e('Subject') ?></th>
                            <th><?= _e('Languages') ?></th>
                            <th style="width: 120px;" class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr id="template" style="display: none;">
                            <td>
                                <select name="subjects[]" class="form-control">
                                    <option value="">...</option>
                                    <?php
                                    foreach ($subjects as $id => $name) {
                                    ?>
                                        <option value="<?= $id ?>"><?= $name ?></option>
                                    <?php } ?>
                                </select>
                            </td>

                            <td>
                                <select name="languages[]" multiple="multiple" class="form-control" style="width: 100%;">
                                    <option value="">...</option>
                                    <?php
                                    foreach ($languages as $id => $name) {
                                    ?>
                                        <option value="<?= $id ?>"><?= $name ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td class="text-center">
                                <a href="javascript:void(0);" class="text-danger"><i class="mdi mdi-trash-can font-size-18 btn-remove-option"></i></a>
                            </td>
                        </tr>
                        <?php if ($userSubjects) { ?>
                            <?php foreach ($userSubjects as $userSubject) { ?>
                                <tr class="tr_item">
                                    <td>
                                        <select name="subjects[]" class="form-control select-subject select-two">
                                            <option value="">...</option>
                                            <?php foreach ($subjects as $id => $name) { ?>
                                                <option value="<?= $id ?>" <?php if ($userSubject['subject'] == $id) echo 'selected'; ?>><?= $name ?></option>
                                            <?php } ?>
                                        </select>
                                    </td>

                                    <td>
                                        <select name="languages[]" multiple="multiple" class="form-control select-lang select-two" style="width: 100%;">
                                            <option value="">...</option>
                                            <?php
                                            foreach ($languages as $id => $name) {
                                            ?>
                                                <option value="<?= $id ?>" <?php if (in_array($id, $userSubject['langs'])) echo 'selected'; ?>><?= $name ?></option>
                                            <?php } ?>
                                        </select>
                                    </td>
                                    <td class="text-center">
                                        <a href="javascript:void(0);" class="text-danger"><i class="mdi mdi-trash-can font-size-18 btn-remove-option"></i></a>
                                    </td>
                                </tr>
                            <? } ?>
                        <? } ?>

                    </tbody>
                </table>
            </div>

            <input type="hidden" id="selected_data" name="data" value="{}"/>

            <div class="mt-3 full-form-btns float-right">
                <?= Html::submitButton('<i class="mdi mdi-save"></i> ' . _e('Save'), ['class' => 'btn btn-success waves-effect']); ?>
                <?= Html::a(_e('Close'), ['subjects'], ['class' => 'btn btn-secondary waves-effect']); ?>
            </div>

        </div>
    </div>
</div>

<?php ActiveForm::end(); ?>

backend/views/users/create.php
<?php
$this->title = _e('New user');
$this->breadcrumbs[] = ['label' => _e('User'), 'url' => $main_url]; ?>

<div class="User-create">
    <?= $this->render('_form', [
        'model' => $model,
        'profile' => $profile,
    ]); ?>
</div>

backend/views/users/error.php
<?php
$this->title = _e('Not found');
$this->breadcrumbs[] = ['label' => _e('User'), 'url' => $main_url]; ?>

<div class="card">
    <div class="card-body page-item-not-found">
        <i class="ri-error-warning-line"></i>
        <h3><?= _e('User not found!'); ?></h3>
        <p><?= _e('The user you were looking for does not exist, unavailable for you or deleted.'); ?></p>

        <a href="<?= $main_url; ?>" class="btn btn-secondary waves-effect btn-with-icon">
            <i class="ri-arrow-left-line mr-1"></i>
            <?= _e('Back to users'); ?>
        </a>
    </div>
</div>

backend/views/users/update.php
<?php
$this->title = _e('Edit user: {email}', [
    'email' => $model->username,
]);

$this->breadcrumb_title = _e('Edit user');
$this->breadcrumbs[] = ['label' => _e('User'), 'url' => $main_url]; ?>

<div class="User-update">
    <?= $this->render('_form',[
        'model' => $model,
        'profile' => $profile,
    ]); ?>
</div>